# This yaml file is for loading local database, server port, disable eureka and set jwt-rest-service endpoint
server:
  port: 8086

POSTGRES_USERNAME: test
POSTGRES_PASSWORD: test
POSTGRES_DBNAME: account2
POSTGRES_SERVICE: localhost:5432
DB_SSLMODE: disable

EUREKA_HOST: localhost:8761
EUREKA_USER: test
EUREKA_PASSWORD: test

eureka:
  client:
    enabled: true

DEFAULT_ZONE: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOST}/eureka

USER_REST_SERVICE: http://user-rest-service
AUTHENTICATION_REST_SERVICE: http://authentication-rest-service
EMAIL_REST_SERVICE: http://email-rest-service
# go through gateway for account-rest-service
ACCOUNT_REST_SERVICE: http://localhost:8080
JWT_REST_SERVICE: http://jwt-rest-service

EMAIL_FROM: ${EMAIL_FROM_USER}

# ISSUER_URL here is used for pulling the public certs from authorization-server for token validation
#ISSUER_URL:  http://10.0.0.28:9001
#ISSUER_URL: http://authorization-server:9001
ISSUER_URL: http://my-server:9001

OAUTH_CLIENTS: oauth-client