logging:
  level:
    root: error
    me:
      sonam: info
info:
  app:
    name: Springboot me.sonam.account.Application
    description: This is a Springboot application
    version: 1.0.0

management:
  endpoint:
    health:
      show-details: always

server:
  port: 8080

spring:
  application:
    name: account-rest-service
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_SERVICE}/${POSTGRES_DBNAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    properties:
      sslMode: ${DB_SSLMODE}


user-rest-service:
    root: ${USER_REST_SERVICE}
    activate: /users/activate/
    delete: /users/

authentication-rest-service:
  root: ${AUTHENTICATION_REST_SERVICE}
  activate: /authentications/activate/
  delete: /authentications/
  update-no-auth-password: /authentications/noauth/password

jwt-service:
  root: ${JWT_REST_SERVICE}
  public-key-id: /jwts/publickeys/{keyId}
  accesstoken: /jwts/accesstoken

email-rest-service:
  root: ${EMAIL_REST_SERVICE}
  emails: /emails

account-rest-service:
  root: ${ACCOUNT_REST_SERVICE}
  activate: /accounts/activate

hmacKey:
  clientId: ${HMAC_CLIENTID}
  algorithm: ${HMAC_ALGORITHM}
  secretKey: ${HMAC_SECRET}

emailFrom: ${EMAIL_FROM}
emailBody: Please click on this link to activate your account
secretExpire: 2

eureka:
  client:
    serviceUrl:
      defaultZone: ${DEFAULT_ZONE}

permitpath:
  - path: /accounts/api/health/*
  - path: /accounts/active/*/*
    httpMethods: GET
  - path: /accounts/activate/*/*
    httpMethods: GET
  - path: /accounts/emailactivationlink/*
    httpMethods: PUT
  - path: /accounts/emailmysecret/*
    httpMethods: PUT
  - path: /accounts/*/*
    httpMethods: POST
  - path: /accounts/email/authenticationId/*
    httpMethods: PUT
  - path: /accounts/validate/secret/*/*
    httpMethods: PUT
  - path: /actuator/info
  - path: /accounts/authentications/password
    httpMethods: PUT

# request to create a jwt token for outbound `email` path when any requestcomes into /accounts/(.)* path (regex)
jwtrequest:
  - in:  /accounts/emailactivationlink/(.)*
    out: /emails
    jwt: request
  - in: /accounts/emailmysecret/(.)*
    out: /emails
    jwt: request
  - in: /accounts/email/authenticationId/(.)*
    out: /emails
    jwt: request
  - in: /accounts/(.)*/(.)*
    out: /emails
    jwt: forward
  - in: /accounts/activate/(.)*/(.)*
    out: /users/activate/(.)*
    jwt: request