# This yaml file is for loading local database, server port, disable eureka and set jwt-rest-service endpoint
server:
  port: 8086

POSTGRES_USERNAME: test
POSTGRES_PASSWORD: test
POSTGRES_DBNAME: account2
POSTGRES_SERVICE: localhost:5432
DB_SSLMODE: disable

EUREKA_HOST: localhost:8761
EUREKA_USER: test
EUREKA_PASSWORD: test

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOST}/eureka

USER_REST_SERVICE: http://user-rest-service
AUTHENTICATION_REST_SERVICE: http://authentication-rest-service
EMAIL_REST_SERVICE: http://email-rest-service
# go through gateway for account-rest-service
ACCOUNT_REST_SERVICE: http://api-gateway:8080

EMAIL_FROM: ${EMAIL_FROM_USER}

ISSUER_ADDRESS: http://api-gateway:9001

# ISSUER_URI here is used for pulling the public certs from authorization-server for token validation
ISSUER_URI: ${ISSUER_ADDRESS}/issuer
OAUTH_AUDIENCES: oauth-client
JWT_SET_URI: ${ISSUER_ADDRESS}/issuer/.well-known/jwks.json

REQUEST_SCOPES: message.read message.write
BASE64_CLIENT_ID_SECRET: b2F1dGgtY2xpZW50Om9hdXRoLXNlY3JldA==