# This yaml file is for loading local database, server port, disable eureka and set jwt-rest-service endpoint
server:
  port: 8086

POSTGRES_USERNAME: test
POSTGRES_PASSWORD: test
POSTGRES_DBNAME: account2
POSTGRES_SERVICE: localhost:5432
DB_SSLMODE: disable

eureka:
  client:
    enabled: false

USER_REST_SERVICE: http://localhost:8084
AUTHENTICATION_REST_SERVICE: http://localhost:8083
EMAIL_REST_SERVICE: http://localhost:8085
ACCOUNT_REST_SERVICE: http://localhost:8086
JWT_REST_SERVICE: http://localhost:8081

hmacKey:
  clientId: account-rest-service
  algorithm: HmacMD5
  secretKey: mysecret

EMAIL_FROM: ${EMAIL_FROM}