logging:
  level:
    root: error
    me:
      sonam: info
info:
  app:
    name: Springboot me.sonam.account.Application
    description: This is a Springboot application
    version: 1.0.0

management:
  endpoint:
    health:
      show-details: always

server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_SERVICE}/${POSTGRES_DBNAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    properties:
      sslMode: ${DB_SSLMODE}


user-rest-service:
    root: ${USER_REST_SERVICE_ROOT}
    activate: /users/activate/
    delete: /user/

authentication-rest-service:
  root: ${AUTHENTICATION_REST_SERVICE_ROOT}
  activate: /authentications/activate/
  delete: /authentications/

email-rest-service: ${EMAIL_REST_SERVICE}

emailFrom: "kecha@sonam.email"
account-activate-link: https://account-rest-service.sonam.cloud/public/accounts/activate
emailBody: Please click on this link to activate your account
secretExpire: 2

eureka:
  client:
    serviceUrl:
      defaultZone: https://${EUREKA_USER}:${EUREKA_PASSWORD}@discovery-service.sonam.cloud/eureka

jwt-rest-service-public-key-id: ${JWT_REST_SERVICE}

me.sonam.jwt-validator:
  permitpath:
    - path: /api/health/*