logging:
  level:
    root: error
    me:
      sonam: info
info:
  app:
    name: Springboot me.sonam.account.Application
    description: This is a Springboot application
    version: 1.0.0

management:
  endpoint:
    health:
      show-details: always

server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_SERVICE}/${POSTGRES_DBNAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    properties:
      sslMode: REQUIRE

activate-authentication-rest-service: http://authentication-rest-service-mychart.backend.svc.cluster.local:80/authentications/activate/
email-rest-service: http://email-rest-service-mychart.backend.svc.cluster.local:80/email
emailFrom: "kecha@sonam.email"
account-activate-link: https://account-rest-service.sonam.cloud/accounts/activate
emailBody: Please click on this link to activate your account
secretExpire: 2